# Generated by Django 5.0.1 on 2025-12-08 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('email', 'Email'), ('number', 'Number'), ('tel', 'Phone Number'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox'), ('date', 'Date Picker'), ('time', 'Time Picker'), ('file', 'File Upload'), ('url', 'URL'), ('range', 'Range Slider')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default_validation', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Form Field Type',
                'verbose_name_plural': 'Form Field Types',
                'db_table': 'form_field_types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_anonymous', models.BooleanField(default=True)),
                ('enable_email_notifications', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Template',
                'verbose_name_plural': 'Form Templates',
                'db_table': 'form_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form_builder.formtemplate')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'db_table': 'form_submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['-submitted_at'], name='form_submis_submitt_ab6a6e_idx'), models.Index(fields=['status'], name='form_submis_status_c1f216_idx')],
            },
        ),
    ]
